import '@violentmonkey/types';

/**
 * Every key of `src/_locales/<language>/messages.json` used by the interface
 */
export interface Translations {
  userjs_name: string;
  userjs_description: string;
  userjs_inject: string;
  userjs_close: string;
  userjs_autoinject: string;
  userjs_fullscreen: string;
  newTab: string;
  newtab_hint: string;
  empty: string;
  search_placeholder: string;
  search_settings: string;
  copy: string;
  copy_all: string;
  close: string;
  download: string;
  download_all: string;
  remove: string;
  remove_all: string;
  open: string;
  min: string;
  max: string;
  issue: string;
  settings: string;
  save: string;
  reset: string;
  general: string;
  theme: string;
  import_export: string;
  import_config: string;
  export_config: string;
  clear_tab_cache: string;
  limit_downloads: string;
  auto_hls: string;
  concurrency: string;
  dtime: string;
  hls_load: string;
  free: string;
  prev: string;
  next: string;
  drm_notice: string;
  play_error: string;
  message: string;
  free_preview: string;
  position: string;
  auto: string;
  'top-left': string;
  'top-right': string;
  'bottom-left': string;
  'bottom-right': string;
  video: string;
  videos: string;
  photo: string;
  photos: string;
  gif: string;
  gifs: string;
  audio: string;
  audios: string;
}

export interface LanguageTranslations {
  en: Translations;
  [language: string]: Partial<Translations>;
}

/**
 * Translation of `key`, falls back to English and finally to `key` itself.
 */
export declare function i18n$(key: keyof Translations | (string & {})): string;

export interface StorageSystem {
  /**
   * Alias of `window.localStorage.getItem`
   */
  getItem<K extends string>(key: K): string | null;

  has<K extends string>(key: K): boolean;

  /**
   * Alias of `window.localStorage.setItem`
   */
  setItem<K extends string, V extends string>(key: K, value: V): void;

  /**
   * Alias of `window.localStorage.removeItem`
   */
  remove<K extends string>(key: K): void;

  /**
   * Set value - Saves key to either GM managed storage or `window.localStorage`
   *
   * [ViolentMonkey Reference](https://violentmonkey.github.io/api/gm/#gm_setvalue)
   */
  setValue<K extends string, V>(key: K, v: V): Promise<void>;

  /**
   * Get value
   *
   * [ViolentMonkey Reference](https://violentmonkey.github.io/api/gm/#gm_getvalue)
   */
  getValue<K extends string, D>(key: K, def?: D): Promise<D>;
}

export interface TransferProgress {
  loaded: number;
  total: number;
}

export interface Network {
  /**
   * Requests a URL.
   *
   * Uses `fetch` when it is preferred (`useFetch`) or when no userscript manager is available,
   * otherwise `GM.xmlHttpRequest` (not restricted by the same-origin policy).
   * Rejects when the status is not `2xx`.
   *
   * `responseType` `basic` resolves the `Response` (`fetch`) / response object (GM), `document` resolves a parsed `Document`.
   *
   * [ViolentMonkey Reference](https://violentmonkey.github.io/api/gm/#gm_xmlhttprequest)
   *
   * [Fetch MDN Reference](https://developer.mozilla.org/docs/Web/API/Fetch_API)
   */
  req(
    url: string | URL,
    method?: string,
    responseType?: string,
    data?: Record<string, any>,
    useFetch?: boolean
  ): Promise<any>;
  format(bytes: number, decimals?: number): string;
  sizes: string[];
  /** Progress of a transfer, `12.5%` or the size when the total is unknown */
  prog(evt: TransferProgress): string;
  /** Requests a page and parses it, nothing in it is executed */
  doc(url: string | URL, data?: Record<string, any>): Promise<Document>;
  /** Streams a response, resolves every chunk */
  fetchChunks(
    url: string | URL,
    data?: Record<string, any>,
    onProgress?: (evt: TransferProgress) => void
  ): Promise<{ chunks: Uint8Array[]; size: number }>;
  /** Downloads through the userscript manager, ignores CORS */
  gmBlob(
    url: string | URL,
    data?: Record<string, any>,
    onProgress?: (evt: TransferProgress) => void
  ): Promise<Blob>;
  /** `fetchChunks`, falls back to `gmBlob` when `fetch` is refused */
  blob(
    url: string | URL,
    data?: Record<string, any>,
    onProgress?: (evt: TransferProgress) => void
  ): Promise<Blob>;
  /** Downloads `url` and saves it as `name` */
  download(
    details: { url: string; name: string; data?: Record<string, any> },
    onProgress?: (evt: TransferProgress) => void
  ): Promise<string>;
}

declare global {
  /** Translations of every language, generated by the builder */
  let translations: LanguageTranslations;
  /** Stylesheet of the interface, generated by the builder */
  let main_css: string;
}
